AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal S3 bucket (dev/prod via parameter)

Parameters:
  ProjectName: { Type: String }
  Env: { Type: String, AllowedValues: [dev, prod] }

Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Env}-data'
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName: { Value: !Ref AppBucket }