AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName: { Type: String, Default: maxmodus, AllowedPattern: '^[a-z0-9-]+$' }
  Env: { Type: String, Default: smbdev, AllowedPattern: '^[a-z0-9-]+$' }
Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
Outputs:
  BucketName: { Value: !Ref TestBucket }
