name: Deploy CloudFormation (this account)

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "stacks/**/*.yaml"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

env:
  AWS_REGION: us-east-2                      # your console shows Ohio
  TEMPLATE_FILE: stacks/s3-buckets.yaml          # set to your actual template path
  STACK_NAME: core-stack
  PARAMS: "ProjectName=maxmodus Env=smbdev" # or whatever your template expects

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (assume role in THIS account)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::201730504434:role/github-actions-deploy   # <- paste ARN from step A3
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-${{ github.run_id }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Validate template
        run: aws cloudformation validate-template --template-body file://${{ env.TEMPLATE_FILE }}

      - name: Deploy
        run: |
          aws cloudformation deploy \
            --stack-name "${{ env.STACK_NAME }}" \
            --template-file "${{ env.TEMPLATE_FILE }}" \
            --parameter-overrides ${{ env.PARAMS }} \
            --no-fail-on-empty-changeset
          # add if your template creates IAM:
          # --capabilities CAPABILITY_NAMED_IAM
