name: Deploy CloudFormation

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - "stacks/**/*.yaml"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  TEMPLATE_FILE: stacks/s3-dynamodb.yaml
  STACK_NAME: my-core-smbdev
  PARAMS: "ProjectName=maxmodus Env=smbdev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (assume role)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::201730504434:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-${{ github.run_id }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Validate template
        run: aws cloudformation validate-template --template-body file://${{ env.TEMPLATE_FILE }}

      - name: Deploy
        run: |
          aws cloudformation deploy \
            --stack-name "${{ env.STACK_NAME }}" \
            --template-file "${{ env.TEMPLATE_FILE }}" \
            --parameter-overrides ${{ env.PARAMS }} \
            --no-fail-on-empty-changeset
          # If your template creates IAM resources, also add:
          # --capabilities CAPABILITY_NAMED_IAM
