name: OIDC STS debug

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/deploy.yml"

  workflow_dispatch:

env:
  AWS_REGION: us-east-2

jobs:
  oidc_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Show repo/ref and files so we know we're on the right branch and the template exists
      - name: Debug repo/ref
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"

      - name: Configure AWS (assume role)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::201730504434:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      # If role assumption works, this prints your caller identity
      - name: Who am I?
        run: aws sts get-caller-identity