name: Deploy CloudFormation

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]
    paths: [ "stacks/**.yaml" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  TEMPLATE_FILE: stacks/s3-dynamodb.yaml
  STACK_NAME_DEV: my-core-dev
  STACK_NAME_SMBDEV: my-core-smbdev
  PARAMS_DEV: "ProjectName=maxmodus Env=dev"
  PARAMS_SMBDEV: "ProjectName=maxmodus Env=smbdev"

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (DEV)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::201730504434:role/github-actions-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate template
        run: aws cloudformation validate-template --template-body file://${{ env.TEMPLATE_FILE }}

      - name: Deploy to DEV
        run: |
          aws cloudformation deploy \
            --stack-name "${{ env.STACK_NAME_DEV }}" \
            --template-file "${{ env.TEMPLATE_FILE }}" \
            --parameter-overrides ${{ env.PARAMS_DEV }} \
            --no-fail-on-empty-changeset